"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { usePathname } from "next/navigation";

interface Tab {
  id: string;
  label: string;
  href: string;
}

const tabs: Tab[] = [
  { id: "dashboard", label: "Dashboard", href: "/dashboard" },
  {
    id: "irrigationSchedule",
    label: "Irrigation Schedule",
    href: "/dashboard/irrigationSchedule",
  },
  {
    id: "profileSettings",
    label: "Profile Settings",
    href: "/dashboard/profileSettings",
  },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <>
      {pathname === "/" ? (
        ""
      ) : (
        <nav className="flex space-x-4 border-b">
          {tabs.map((tab) => (
            <Link key={tab.id} href={tab.href}>
              <span
                className={`py-2 px-4 cursor-pointer ${
                  pathname === tab.href
                    ? "border-b-2 border-blue-500 text-blue-500"
                    : ""
                }`}
              >
                {tab.label}
              </span>
            </Link>
          ))}
        </nav>
      )}
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased container m-auto py-10`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
